# 201 Torch and Numpy

View more, visit my tutorial page: https://mofanpy.com/tutorials/
My Youtube Channel: https://www.youtube.com/user/MorvanZhou

Dependencies:
* torch: 0.1.11
* numpy

Details about math operation in torch can be found in: http://pytorch.org/docs/torch.html#math-operations


In [1]:
import torch
import numpy as np

In [2]:
# convert numpy to tensor or vise versa
np_data = np.arange(6).reshape((2, 3))
torch_data = torch.from_numpy(np_data)
tensor2array = torch_data.numpy()
print(
    '\nnumpy array:', np_data,          # [[0 1 2], [3 4 5]]
    '\ntorch tensor:', torch_data,      #  0  1  2 \n 3  4  5    [torch.LongTensor of size 2x3]
    '\ntensor to array:', tensor2array, # [[0 1 2], [3 4 5]]
)


numpy array: [[0 1 2]
 [3 4 5]] 
torch tensor: tensor([[0, 1, 2],
        [3, 4, 5]]) 
tensor to array: [[0 1 2]
 [3 4 5]]


In [3]:
# abs
data = [-1, -2, 1, 2]
tensor = torch.FloatTensor(data)  # 32-bit floating point
print(
    '\nabs',
    '\nnumpy: ', np.abs(data),          # [1 2 1 2]
    '\ntorch: ', torch.abs(tensor)      # [1 2 1 2]
)


abs 
numpy:  [1 2 1 2] 
torch:  tensor([1., 2., 1., 2.])


In [4]:
tensor.abs()

tensor([1., 2., 1., 2.])

In [5]:
# sin
print(
    '\nsin',
    '\nnumpy: ', np.sin(data),      # [-0.84147098 -0.90929743  0.84147098  0.90929743]
    '\ntorch: ', torch.sin(tensor)  # [-0.8415 -0.9093  0.8415  0.9093]
)


sin 
numpy:  [-0.84147098 -0.90929743  0.84147098  0.90929743] 
torch:  tensor([-0.8415, -0.9093,  0.8415,  0.9093])


In [6]:
tensor.sigmoid()

tensor([ 0.2689,  0.1192,  0.7311,  0.8808])

In [7]:
tensor.exp()

tensor([ 0.3679,  0.1353,  2.7183,  7.3891])

In [8]:
# mean
print(
    '\nmean',
    '\nnumpy: ', np.mean(data),         # 0.0
    '\ntorch: ', torch.mean(tensor)     # 0.0
)


mean 
numpy:  0.0 
torch:  tensor(0.)


In [2]:
# matrix multiplication
data = [[1,2], [3,4]]
tensor = torch.FloatTensor(data)  # 32-bit floating point
# correct method
print(
    '\nmatrix multiplication (matmul)',
    '\nnumpy: ', np.matmul(data, data),     # [[7, 10], [15, 22]]
    '\ntorch: ', torch.mm(tensor, tensor)   # [[7, 10], [15, 22]]
)


matrix multiplication (matmul) 
numpy:  [[ 7 10]
 [15 22]] 
torch:  tensor([[ 7., 10.],
        [15., 22.]])


#### numpy中，matrix1.dot(matrix2) 等价 np.matmul(matrix1, matrix2)
#### pytorch中，tensor1.dot(tensor2)只允许一维计算内积

In [10]:
# incorrect method
data = [[1,2], [3,4]]
data = np.array(data)
tensor = torch.Tensor(data)
data.dot(data)
print(
    '\nmatrix multiplication (dot)',
    '\nnumpy: ', data.dot(data),        # [[7, 10], [15, 22]]
    '\ntorch: ', tensor.dot(tensor)    # NOT WORKING! Beware that torch.dot does not broadcast, only works for 1-dimensional tensor
)

array([[ 7, 10],
       [15, 22]])

RuntimeError: 1D tensors expected, but got 2D and 2D tensors

Note that:

torch.dot(tensor1, tensor2) → float

Computes the dot product (inner product) of two tensors. Both tensors are treated as 1-D vectors.

In [10]:
tensor.mm(tensor)

tensor([[  7.,  10.],
        [ 15.,  22.]])

#### 逐个位置元素相乘

In [11]:
tensor * tensor

tensor([[  1.,   4.],
        [  9.,  16.]])

In [13]:
torch.dot(torch.Tensor([2, 3]), torch.Tensor([2, 1]))

tensor(7.)

#### torch.cat()

In [28]:
x1 = torch.tensor([[11,21,31],[21,31,41]],dtype=torch.int)
# x1.shape # torch.Size([2, 3])
x1


x2 = torch.tensor([[12,22,32],[22,32,42]],dtype=torch.int)
# x2.shape  # torch.Size([2, 3])
x2

tensor([[11, 21, 31],
        [21, 31, 41]], dtype=torch.int32)

tensor([[12, 22, 32],
        [22, 32, 42]], dtype=torch.int32)

In [30]:
inputs = [x1, x2]
torch.cat(inputs, dim=0).shape
torch.cat(inputs, dim=1).shape
torch.cat(inputs, dim=2).shape

torch.Size([4, 3])

torch.Size([2, 6])

IndexError: Dimension out of range (expected to be in range of [-2, 1], but got 2)

#### torch.normal()

In [23]:
n_data = torch.ones(3, 2)
n_data

# 以下等价
# 均值为2，方差为1的tensor
x0 = torch.normal(2*n_data, 1)      # class0 x data (tensor), shape=(100, 2)
x1 = torch.normal(2, 1, size=n_data.shape) 
x0
x1

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

tensor([[1.6240, 3.9728],
        [2.2436, 1.6678],
        [2.2064, 2.2010]])

tensor([[2.1614, 2.2841],
        [2.1946, 3.1991],
        [1.3020, 2.0481]])

In [25]:
x = torch.tensor([[1.0,1.0, 1.0, 1.0, 1.0],[2.0,2.0,2.0,2.0,2.0]])
torch.normal(x, 1) 

tensor([[ 0.2275,  1.7848, -0.1732,  1.1750,  1.5804],
        [ 1.8737,  1.7338,  0.6046,  1.6957,  0.6215]])

#### .type()

In [33]:
n_data = torch.ones(3, 2)
n_data.dtype
n_data = n_data.type(torch.FloatTensor)
n_data.dtype
n_data = n_data.type(torch.LongTensor)
n_data.dtype

torch.float32

torch.float32

torch.int64

####  torch.max()

In [41]:
_, prediction = torch.max(torch.tensor([[0.0900, 0.6652, 0.2447],
        [0.0900, 0.2447, 0.6652]]), 1)
_
prediction
prediction.data.numpy().squeeze()

tensor([0.6652, 0.6652])

tensor([1, 2])

array([1, 2])

In [39]:
# 2*3, 对3个取max
torch.max(torch.tensor([[0.0900, 0.6652, 0.2447],
        [0.0900, 0.2447, 0.6652]]), 1)

torch.return_types.max(
values=tensor([0.6652, 0.6652]),
indices=tensor([1, 2]))

#### F.softmax(out) 不改变维度

In [35]:
import torch.nn.functional as F
out = torch.tensor([[1.0,3.0, 2.0],[1.0,2.0, 3.0]])
F.softmax(out)

/var/folders/fc/hlff0j413bs7qvny_cknz7400000gn/T/ipykernel_2732/2184643305.py:3: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  F.softmax(out)


tensor([[0.0900, 0.6652, 0.2447],
        [0.0900, 0.2447, 0.6652]])

#### unsqueeze, squeeze
以下等价  
纬度转变（5，）-> (5,1)      
tensor1.unsqueeze(dim=1)     
torch.unsqueeze(tensor1, dim=1) 

纬度转变（5，）-> (1,5)      
tensor1.unsqueeze(dim=0)     

In [50]:
a.unsqueeze(dim=0) 

tensor([[-1.0000, -0.5000,  0.0000,  0.5000,  1.0000]])

In [51]:
a = torch.linspace(-1, 1, 5) # （5,）
a.shape
b = torch.unsqueeze(a, dim=0) # (1,5)
b
b.squeeze()
b = torch.unsqueeze(a, dim=1) # (5,1)
b
b.squeeze()

torch.Size([5])

tensor([[-1.0000, -0.5000,  0.0000,  0.5000,  1.0000]])

tensor([-1.0000, -0.5000,  0.0000,  0.5000,  1.0000])

tensor([[-1.0000],
        [-0.5000],
        [ 0.0000],
        [ 0.5000],
        [ 1.0000]])

tensor([-1.0000, -0.5000,  0.0000,  0.5000,  1.0000])

tensor([[0.1702],
        [0.9062],
        [0.2094],
        [0.4600],
        [0.0204]])

#### torch.rand
0到1之间的随机数

In [54]:
torch.rand(3,4)  

tensor([[0.5236, 0.6239, 0.4030, 0.6044],
        [0.3770, 0.8355, 0.4010, 0.6421],
        [0.9987, 0.4850, 0.0314, 0.4333]])